layout_spectrum: 0.37706146886839653
typography_spectrum: 0.35609099018470486
color:
  brandStrength: 0.8523600049270778
  lightness: 0.8114702468317482
  saturation: 0.38523659286301326
  rhythmicContrast: 0.8825087258741628
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
github: true
analytics:
  google: UA-110487-30
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4e4e66c9-7eaa-4158-a5d8-9e25f41a5ee4.png
name: musik.pro
navigation:
  - name: Über "meine" Musik-Streaming Dienste
    id: dd1e0d5b-d963-4a62-9926-c179bfab914b
    type: content
  - name: Über musik.pro
    id: c6bf62f4-ca7a-477e-8af2-2dfd85f66254
    type: content
  - name: Homepage
    url: 'http://musik.pro'
    type: external
title: Musik + Streaming
description: Gestreamte Linkschleuderei.
purpose:
  - type: external
    url: 'http://musik.pro/rss.xml'
    label: Abonnieren / RSS
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b8c18721-6d1b-4d8a-a42d-00e4ff4eadbf.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b8c18721-6d1b-4d8a-a42d-00e4ff4eadbf.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c1abf5df-89ed-4006-813a-6a04392e27d5.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c1abf5df-89ed-4006-813a-6a04392e27d5.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
